---
title: "clock"
author: "Scott Chamberlain"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{clock}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Time classes for R, w/ time mocking capability via [timefuzz][]

```{r setup}
library(clock)
```

## clock

```{r}
clock(2009)$time
clock(2009, 3, 13)$time
clock(2009, 3, 13, 1, 4, 53)$time
```

```{r}
x <- clock(2009, 3, 13)
x$utc
x$date
```

## now

```{r}
now()$now()
now("UTC")$now()
```

## sys_date

Mockable [Sys.Date()] drop in replacement. Uses `now()` internally so can be mocked as shown below.

```{r}
Sys.Date()
sys_date()
```

## sys_time

Mockable [Sys.time()] drop in replacement. Uses `now()` internally so can be mocked as shown below.

```{r}
Sys.time()
sys_time()
```

## use in a function

```{r}
todays_date <- function() sys_time()
todays_date()
```

now let's mock time

```{r}
library(timefuzz)
x <- time_fuzz$new()
## set to today + 5 days
x$freeze(Sys.Date() + 5)
todays_date()
# if you run it again, you get the same EXACT time
todays_date()
```

"unfreeze" and you're back to real time

```{r}
x$unfreeze()
todays_date()
Sys.sleep(1)
todays_date()
Sys.sleep(1)
todays_date()
```

[timefuzz]: https://github.com/ropensci/timefuzz
